export enum FactCategory {
  USER_SKILL = "USER_SKILL",
  SOP = "SOP",
  PROJECT_RULE = "PROJECT_RULE",
  LESSON_LEARNED = "LESSON_LEARNED",
  PREFERENCE = "PREFERENCE",
  PEOPLE = "PEOPLE",
  TERMINOLOGY = "TERMINOLOGY",
  OTHER = "OTHER"
}

export enum FactSource {
  USER_TAUGHT = "USER_TAUGHT",
  AI_OBSERVED = "AI_OBSERVED",
  IMPORTED = "IMPORTED"
}
